### ISSUE TITLE
No vibration at end of session

### ISSUE THREAD

**Issue by pauloue** [goodtime-productivity/Goodtime#116]
In the latest version I'm not getting a vibration at the end of a session.

**Comment by adrcotfas** [comment]
What device are you using? This is not reproducible on any of my devices and no one reported this until now.

**Comment by pauloue** [comment]
It's a Moto G5 plus. In system setting the notification priority is set to medium (the default I think) and in the app vibrate is on and sound is off. Also when a session finishes the app is automatically opened which seems odd.

**Comment by adrcotfas** [comment]
You can ignore the notification channel options because those are used only to show the notification, not for sound and vibration. The fact that the app gets brought to front is intentional.
Does the sound work for you? Does the vibration work for you in other apps? At the moment, I have no idea about what can cause your problem.

**Comment by pauloue** [comment]
I got it working by changing the Default notification sound in system notification settings from None to a sound. I would expect vibrations to be unaffected by this setting. Notification vibrations do work for other apps.
