### ISSUE TITLE
Option to clear data in Statistics Chart

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [goodtime-productivity/Goodtime#120]
Was testing the app features before starting to use it for real. Therefore created few labels and completed 1 session.

In order to start using the app for real, cleared dummy labels. But, the stats page counts the dummy session and still displays it.

**Comment by adrcotfas** [comment]
I'm not sure if I get your point but any finished/skipped/stopped session of at least 1 minute will be stored in the statistics independent of its label.
It will be stored without a label if no label was selected from the bottom right button from the main page.
If you have sessions stored under any label and you delete that label, the sessions will not be deleted but will loose their label.

The sessions counter from the main page displays the number of today's finished sessions and since 2.0.5 the old behavior was implemented, which is: click on it to reset today's finished sessions.

**Comment by PrasannaVenkadesh** [comment]
Sorry, I should have mentioned the version. I am using 2.0.3 from f-droid (that is the latest version present there).

Yes, your description is correct. So, irrespective of labels, how can I remove such dummy sessions?

**Comment by adrcotfas** [comment]
To delete any session, go to the Statistics -> list -> long click on any session.
